# .github/workflows/deploy.yml

name: Deploy VitePress Site

on:
  push:
    branches: [main] # This triggers the workflow on every push to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Build your site
      - name: Build
        run: npm run docs:build

          # --- ADD THIS NEW STEP ---
      - name: List files in the repository
        run: ls -R

      # Deploy the built site to the gh-pages branch
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: /.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}